--- 
- hosts: 172.31.44.183
  become: yes
  tasks:
  - name: install git
    dnf:
     name: git
     state: present
    tags: mygit

  - name: install tree 
    dnf:
     name: tree
     state: present
    tags: mytree